create schema if not exists "DS";

create table if not exists "DS".FT_BALANCE_F (
    "ON_DATE" DATE not null,
    "ACCOUNT_RK" NUMERIC not null,
    "CURRENCY_RK" NUMERIC,
    "BALANCE_OUT" FLOAT,
    primary key ("ON_DATE", "ACCOUNT_RK")
);

create table if not exists "DS".FT_POSTING_F (
    "OPER_DATE" DATE not null,
    "CREDIT_ACCOUNT_RK" NUMERIC not null,
    "DEBET_ACCOUNT_RK" NUMERIC not null,
    "CREDIT_AMOUNT" FLOAT,
    "DEBET_AMOUNT" FLOAT
);

create table if not exists "DS".MD_ACCOUNT_D (
    "DATA_ACTUAL_DATE" DATE not null,
    "DATA_ACTUAL_END_DATE" DATE not null,
    "ACCOUNT_RK" NUMERIC not null,
    "ACCOUNT_NUMBER" VARCHAR(20) not null,
    "CHAR_TYPE" VARCHAR(1) not null,
    "CURRENCY_RK" NUMERIC not null,
    "CURRENCY_CODE" VARCHAR(3) not null,
    primary key ("DATA_ACTUAL_DATE", "ACCOUNT_RK")
);

create table if not exists "DS".MD_CURRENCY_D (
    "CURRENCY_RK" NUMERIC not null,
    "DATA_ACTUAL_DATE" DATE not null,
    "DATA_ACTUAL_END_DATE" DATE,
    "CURRENCY_CODE" VARCHAR(3),
    "CODE_ISO_CHAR" VARCHAR(3),
    primary key ("CURRENCY_RK", "DATA_ACTUAL_DATE")
);

create table if not exists "DS".MD_EXCHANGE_RATE_D (
    "DATA_ACTUAL_DATE" DATE not null,
    "DATA_ACTUAL_END_DATE" DATE,
    "CURRENCY_RK" NUMERIC not null,
    "REDUCED_COURCE" FLOAT,
    "CODE_ISO_NUM" VARCHAR(3),
    primary key ("DATA_ACTUAL_DATE", "CURRENCY_RK")
);

create table if not exists "DS".MD_LEDGER_ACCOUNT_S (
    "CHAPTER" CHAR(1),
    "CHAPTER_NAME" VARCHAR(16),
    "SECTION_NUMBER" INTEGER,
    "SECTION_NAME" VARCHAR(22),
    "SUBSECTION_NAME" VARCHAR(21),
    "LEDGER1_ACCOUNT" INTEGER,
    "LEDGER1_ACCOUNT_NAME" VARCHAR(47),
    "LEDGER_ACCOUNT" INTEGER not null,
    "LEDGER_ACCOUNT_NAME" VARCHAR(153),
    "CHARACTERISTIC" CHAR(1),
    "IS_RESIDENT" INTEGER,
    "IS_RESERVE" INTEGER,
    "IS_RESERVED" INTEGER,
    "IS_LOAN" INTEGER,
    "IS_RESERVED_ASSETS" INTEGER,
    "IS_OVERDUE" INTEGER,
    "IS_INTEREST" INTEGER,
    "PAIR_ACCOUNT" VARCHAR(5),
    "START_DATE" DATE not null,
    "END_DATE" DATE,
    "IS_RUB_ONLY" INTEGER,
    "MIN_TERM" VARCHAR(1),
    "MIN_TERM_MEASURE" VARCHAR(1),
    "MAX_TERM" VARCHAR(1),
    "MAX_TERM_MEASURE" VARCHAR(1),
    "LEDGER_ACC_FULL_NAME_TRANSLIT" VARCHAR(1),
    "IS_REVALUATION" VARCHAR(1),
    "IS_CORRECT" VARCHAR(1),
    primary key ("LEDGER_ACCOUNT", "START_DATE")
);

create schema if not exists "LOGS";

create table if not exists "LOGS".LOGS(
    "ID" SERIAL PRIMARY KEY,
    "STATUS" VARCHAR,
    "TIME" TIMESTAMPTZ
);

create schema if not exists "DM";

create table if not exists "DM".DM_ACCOUNT_TURNOVER_F(
    "ON_DATE" DATE,
    "ACCOUNT_RK" NUMERIC,
    "CREDIT_AMOUNT" NUMERIC(23,8),
    "CREDIT_AMOUNT_RUB" NUMERIC(23,8),
    "DEBET_AMOUNT" NUMERIC(23,8),
    "DEBET_AMOUNT_RUB" NUMERIC(23,8)
);

create table if not exists "DM".DM_ACCOUNT_BALANCE_F(
    "ON_DATE" DATE,
    "ACCOUNT_RK" NUMERIC,
    "BALANCE_OUT" NUMERIC,
    "BALANCE_OUT_RUB" NUMERIC
);

create table if not exists "DM".DM_F101_ROUND_F(
    "FROM_DATE" DATE,
    "TO_DATE" DATE,
    "CHAPTER" VARCHAR(1),
    "LEDGER_ACCOUNT" VARCHAR(5),
    "CHARACTERISTIC" VARCHAR(1),
    "BALANCE_IN_RUB" NUMERIC(23,8),
    "R_BALANCE_IN_RUB" NUMERIC(23,8),
    "BALANCE_IN_VAL" NUMERIC(23,8),
    "R_BALANCE_IN_VAL" NUMERIC(23,8),
    "BALANCE_IN_TOTAL" NUMERIC(23,8),
    "R_BALANCE_IN_TOTAL" NUMERIC(23,8),
    "TURN_DEB_RUB" NUMERIC(23,8),
    "R_TURN_DEB_RUB" NUMERIC(23,8),
    "TURN_DEB_VAL" NUMERIC(23,8),
    "R_TURN_DEB_VAL" NUMERIC(23,8),
    "TURN_DEB_TOTAL" NUMERIC(23,8),
    "R_TURN_DEB_TOTAL" NUMERIC(23,8),
    "TURN_CRE_RUB" NUMERIC(23,8),
    "R_TURN_CRE_RUB" NUMERIC(23,8),
    "TURN_CRE_VAL" NUMERIC(23,8),
    "R_TURN_CRE_VAL" NUMERIC(23,8),
    "TURN_CRE_TOTAL" NUMERIC(23,8),
    "R_TURN_CRE_TOTAL" NUMERIC(23,8),
    "BALANCE_OUT_RUB" NUMERIC(23,8),
    "R_BALANCE_OUT_RUB" NUMERIC(23,8),
    "BALANCE_OUT_VAL" NUMERIC(23,8),
    "R_BALANCE_OUT_VAL" NUMERIC(23,8),
    "BALANCE_OUT_TOTAL" NUMERIC(23,8),
    "R_BALANCE_OUT_TOTAL" NUMERIC(23,8)
);
